version: '3'
services:
  mongo:
    image: mongo:3.4
    container_name: ${COMPOSE_PROJECT_NAME}_mongo
    networks:
      - unifi
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    volumes:
      - /volume1/docker/unifi/db:/data/db
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    container_name: ${COMPOSE_PROJECT_NAME}_controller
    depends_on:
      - mongo
    init: true
    networks:
      - unifi
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
    volumes:
      - /volume1/docker/unifi/data:/unifi/data
      - /volume1/docker/unifi/log:/unifi/log
      - /volume1/docker/unifi/cert:/unifi/cert
      - /volume1/docker/unifi/init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      RUNAS_UID0: 'false'
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
  logs:
    image: bash
    container_name: ${COMPOSE_PROJECT_NAME}_logs
    depends_on:
      - controller
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: always
    volumes:
      - /volume1/docker/unifi/log:/unifi/log

networks:
  unifi:
